project_id = "rpeaehxawjvbhdneglce"

[functions.analyze-resume]
verify_jwt = false

[functions.threads-sync]
verify_jwt = false

[functions.analytics-export]
verify_jwt = false

[functions.process-email-queue]
verify_jwt = true