import { CustomizeSettings, DEFAULT_CUSTOMIZE } from "./customizeTypes";

export interface TemplatePresetInfo {
  id: string;
  name: string;
  desc: string;
}

export const TEMPLATE_LIST: TemplatePresetInfo[] = [
  { id: "classic", name: "Classic", desc: "Centered header, serif-style, traditional layout" },
  { id: "modern", name: "Modern", desc: "Clean sans-serif, teal accent, compact spacing" },
  { id: "professional", name: "Professional", desc: "Navy accent, bar headings, bold subtitles" },
  { id: "minimal", name: "Minimal", desc: "Maximum whitespace, all black/gray, sparse" },
  { id: "executive", name: "Executive", desc: "Large name, uppercase headings, charcoal tones" },
];

export const TEMPLATE_PRESETS: Record<string, Partial<CustomizeSettings>> = {
  modern: {
    columns: "one",
    headingStyle: "plain",
    headingSize: "m",
    headingUppercase: false,
    headerAlign: "left",
    headerArrangement: "stacked",
    contactSeparator: "bar",
    headerIconStyle: "none",
    accentColor: "#0891b2",
    nameSize: "m",
    nameBold: true,
    nameFont: "body",
    bodyFont: "'Inter', sans-serif",
    headingFont: "'Inter', sans-serif",
    fontSize: 10.5,
    lineHeight: 1.4,
    marginX: 16,
    marginY: 16,
    sectionSpacing: 4,
    colorMode: "basic",
    nameColor: "#111827",
    titleColor: "#6B7280",
    headingsColor: "#0891b2",
    a4Background: "#ffffff",
  },

  classic: {
    columns: "one",
    headingStyle: "underline",
    headingSize: "m",
    headingUppercase: true,
    headerAlign: "center",
    headerArrangement: "stacked",
    contactSeparator: "icon",
    headerIconStyle: "outline",
    accentColor: "#1e293b",
    nameSize: "s",
    nameBold: true,
    nameFont: "body",
    bodyFont: "'Lora', serif",
    headingFont: "'Lora', serif",
    fontSize: 11,
    lineHeight: 1.5,
    marginX: 16,
    marginY: 16,
    sectionSpacing: 5,
    colorMode: "basic",
    nameColor: "#111827",
    titleColor: "#6B7280",
    headingsColor: "#111827",
    a4Background: "#ffffff",
  },

  professional: {
    columns: "one",
    headingStyle: "left-accent",
    headingSize: "m",
    headingUppercase: true,
    headerAlign: "left",
    headerArrangement: "stacked",
    contactSeparator: "bar",
    headerIconStyle: "none",
    accentColor: "#1e3a5f",
    nameSize: "l",
    nameBold: true,
    nameFont: "body",
    bodyFont: "'Source Serif 4', serif",
    headingFont: "'Source Serif 4', serif",
    fontSize: 11,
    lineHeight: 1.5,
    marginX: 18,
    marginY: 18,
    sectionSpacing: 5,
    colorMode: "basic",
    nameColor: "#1e3a5f",
    titleColor: "#6B7280",
    headingsColor: "#1e3a5f",
    a4Background: "#ffffff",
  },

  minimal: {
    columns: "one",
    headingStyle: "plain",
    headingSize: "m",
    headingUppercase: false,
    headerAlign: "left",
    headerArrangement: "stacked",
    contactSeparator: "bar",
    headerIconStyle: "none",
    accentColor: "#374151",
    nameSize: "m",
    nameBold: true,
    nameFont: "body",
    bodyFont: "'Inter', sans-serif",
    headingFont: "'Inter', sans-serif",
    fontSize: 10.5,
    lineHeight: 1.45,
    marginX: 22,
    marginY: 22,
    sectionSpacing: 6,
    colorMode: "basic",
    nameColor: "#374151",
    titleColor: "#9CA3AF",
    headingsColor: "#374151",
    a4Background: "#ffffff",
  },

  "two-column": {
    columns: "two",
    columnRatio: 5,
    headingStyle: "underline",
    headingSize: "m",
    headingUppercase: true,
    headerAlign: "center",
    headerArrangement: "stacked",
    contactSeparator: "bullet",
    headerIconStyle: "none",
    accentColor: "#374151",
    nameSize: "m",
    nameBold: true,
    nameFont: "body",
    bodyFont: "'Mulish', sans-serif",
    headingFont: "'Mulish', sans-serif",
    fontSize: 10,
    lineHeight: 1.4,
    marginX: 14,
    marginY: 14,
    sectionSpacing: 4,
    colorMode: "basic",
    nameColor: "#111827",
    titleColor: "#6B7280",
    headingsColor: "#374151",
    a4Background: "#ffffff",
  },

  sidebar: {
    columns: "mix",
    columnRatio: 4,
    headingStyle: "left-accent",
    headingSize: "m",
    headingUppercase: true,
    headerAlign: "left",
    headerArrangement: "stacked",
    contactSeparator: "icon",
    headerIconStyle: "filled",
    accentColor: "#7c3aed",
    nameSize: "s",
    nameBold: true,
    nameFont: "body",
    bodyFont: "'Nunito', sans-serif",
    headingFont: "'Nunito', sans-serif",
    fontSize: 10.5,
    lineHeight: 1.45,
    marginX: 14,
    marginY: 14,
    sectionSpacing: 5,
    colorMode: "advanced",
    nameColor: "#f1f5f9",
    titleColor: "#94a3b8",
    headingsColor: "#111827",
    a4Background: "#ffffff",
  },

  executive: {
    columns: "one",
    headingStyle: "full-underline",
    headingSize: "l",
    headingUppercase: true,
    headerAlign: "center",
    headerArrangement: "stacked",
    contactSeparator: "bullet",
    headerIconStyle: "none",
    accentColor: "#1f2937",
    nameSize: "xl",
    nameBold: true,
    nameFont: "creative",
    bodyFont: "'Crimson Pro', serif",
    headingFont: "'Crimson Pro', serif",
    fontSize: 11,
    lineHeight: 1.5,
    marginX: 20,
    marginY: 20,
    sectionSpacing: 6,
    colorMode: "basic",
    nameColor: "#1f2937",
    titleColor: "#6B7280",
    headingsColor: "#1f2937",
    a4Background: "#ffffff",
  },

  creative: {
    columns: "two",
    columnRatio: 4,
    headingStyle: "background",
    headingSize: "m",
    headingUppercase: true,
    headerAlign: "left",
    headerArrangement: "stacked",
    contactSeparator: "icon",
    headerIconStyle: "filled",
    accentColor: "#f97316",
    nameSize: "m",
    nameBold: true,
    nameFont: "creative",
    bodyFont: "'Nunito', sans-serif",
    headingFont: "'Poppins', sans-serif",
    fontSize: 10.5,
    lineHeight: 1.45,
    marginX: 14,
    marginY: 14,
    sectionSpacing: 5,
    colorMode: "advanced",
    nameColor: "#f97316",
    titleColor: "#6B7280",
    headingsColor: "#ffffff",
    a4Background: "#ffffff",
  },
};

/**
 * Apply a template preset: merges preset styling on top of defaults,
 * preserving user content-related choices.
 */
export function applyTemplatePreset(
  current: CustomizeSettings,
  templateId: string
): CustomizeSettings {
  const preset = TEMPLATE_PRESETS[templateId];
  if (!preset) return { ...current, template: templateId };

  const preserved = {
    language: current.language,
    dateFormat: current.dateFormat,
    pageFormat: current.pageFormat,
    shareAsTemplate: current.shareAsTemplate,
    showPageNumbers: current.showPageNumbers,
    showFooterSignature: current.showFooterSignature,
    linkUnderline: current.linkUnderline,
    linkBlue: current.linkBlue,
    linkIcon: current.linkIcon,
    linkIconStyle: current.linkIconStyle,
  };

  return {
    ...DEFAULT_CUSTOMIZE,
    ...preset,
    ...preserved,
    template: templateId,
  };
}
