
INSERT INTO public.interview_questions (id, question_en, question_zh, category, tags, difficulty, audience, source) VALUES
(69, 'What kind of money would you be interested in making?', '你期望的薪資水準是多少？', 'salary_comp', '{salary,expectations,negotiation}', 3, '{all}', 'book1'),
(70, 'What makes you unique?', '是什麼讓你與眾不同？', 'self_assessment', '{unique_value,personal_brand,differentiation}', 2, '{all}', 'book1'),
(71, 'What motivates you?', '什麼事情能夠激勵你？', 'motivation_values', '{motivation,drive,values}', 1, '{all}', 'book1'),
(72, 'What questions do you have for us?', '你有什麼問題想問我們？', 'company_knowledge', '{questions,engagement,curiosity}', 1, '{all}', 'book1'),
(73, 'What salary are you looking for?', '你期望的薪資是多少？', 'salary_comp', '{salary,negotiation,expectations}', 3, '{all}', 'book1'),
(74, 'What type of work environment do you prefer?', '你偏好什麼樣的工作環境？', 'culture_fit', '{environment,culture,preferences}', 1, '{all}', 'book1'),
(75, 'What was the last book you read?', '你最近讀的一本書是什麼？', 'culture_fit', '{reading,personality,growth}', 1, '{all}', 'book1'),
(76, 'What was your least favorite part of your last job?', '你上一份工作中最不喜歡的部分是什麼？', 'career_history', '{past_jobs,preferences,honesty}', 2, '{all}', 'book1'),
(77, 'What was your most difficult work experience and how did you deal with it?', '你遇過最困難的工作經歷是什麼？你是如何應對的？', 'behavioral', '{adversity,resilience,problem_solving}', 2, '{all}', 'book1'),
(78, 'What were the major challenges of your last job and how did you handle them?', '你上一份工作的主要挑戰是什麼？你是如何應對的？', 'behavioral', '{challenges,problem_solving,past_jobs}', 2, '{all}', 'book1'),
(79, 'What were your responsibilities in your last job?', '你上一份工作的職責是什麼？', 'career_history', '{responsibilities,experience,past_jobs}', 1, '{all}', 'book1'),
(80, 'What will you contribute to this job?', '你會為這份工作帶來什麼貢獻？', 'self_assessment', '{value_proposition,contribution,skills}', 2, '{all}', 'book1'),
(81, 'What will you do if you don''t get this position?', '如果你沒有獲得這個職位，你會怎麼做？', 'situational', '{resilience,alternatives,composure}', 2, '{all}', 'book1'),
(82, 'What would you do first at this job?', '到任後你會先做什麼？', 'situational', '{onboarding,priorities,initiative}', 2, '{mid,senior}', 'book1'),
(83, 'What would your friends tell me about you?', '你的朋友會如何形容你？', 'self_assessment', '{personality,references,self_awareness}', 1, '{all}', 'book1'),
(84, 'What would your manager say was the area you needed most development in?', '你的主管會說你最需要發展的領域是什麼？', 'strengths_weaknesses', '{development,weaknesses,feedback}', 2, '{all}', 'book1'),
(85, 'What can you do to make this company better?', '你能為這家公司做些什麼使其變得更好？', 'self_assessment', '{value_proposition,improvement,vision}', 2, '{mid,senior}', 'book1'),
(86, 'Where do you see yourself in 5 years?', '你對自己五年後的規劃是什麼？', 'career_history', '{career_goals,future,ambition}', 1, '{all}', 'book1'),
(87, 'Who was your best boss and who was your worst?', '誰是你遇過最好的主管？誰是最差的？', 'behavioral', '{boss_relationship,preferences,honesty}', 2, '{all}', 'book1'),
(88, 'Why are you looking to leave your current job?', '你為什麼想離開目前的工作？', 'career_history', '{motivation,current_job,reasons}', 2, '{all}', 'book1'),
(89, 'Why did you freelance for so long?', '你為什麼從事自由接案工作這麼長時間？', 'career_history', '{freelance,career_path,explanation}', 2, '{career_changer}', 'book1'),
(90, 'Why did you leave your last position?', '你為什麼離開上一份工作？', 'career_history', '{departure,reasons,honesty}', 2, '{all}', 'book1'),
(91, 'Why did you take a job that seems to be outside of your career path?', '你為什麼接了一份看起來不在你職涯路徑上的工作？', 'career_history', '{career_change,explanation,path}', 2, '{career_changer}', 'book1'),
(92, 'Why do you believe you are the best fit for this position?', '你為什麼認為你是這個職位的最佳人選？', 'self_assessment', '{fit,value_proposition,confidence}', 2, '{all}', 'book1'),
(93, 'Why do you have a big gap in your employment history?', '你的就業紀錄為什麼有一段很長的空白期？', 'career_history', '{gap,explanation,honesty}', 3, '{career_changer}', 'book1'),
(94, 'Why do you think you can manage a team without any prior managerial experience?', '你沒有管理經驗，為什麼認為自己能夠帶領團隊？', 'management_leadership', '{management,leadership,first_time}', 3, '{mid}', 'book1'),
(95, 'Why do you want to join this company?', '你為什麼想加入這家公司？', 'company_knowledge', '{motivation,company_fit,research}', 1, '{all}', 'book1'),
(96, 'Why do you want to switch from an academic field to business/industry?', '你為什麼想從學術領域轉到商業／產業界？', 'career_history', '{career_change,academia,transition}', 3, '{career_changer}', 'book1'),
(97, 'Why do you want to work for someone else after owning your own business / freelancing?', '在擁有自己的事業／從事自由接案工作之後，你為什麼想要為他人工作？', 'career_history', '{freelance,career_change,transition}', 3, '{career_changer}', 'book1'),
(98, 'Why have you been out of work for so long?', '你為什麼這麼長時間沒有工作？', 'career_history', '{unemployment,gap,explanation}', 3, '{career_changer}', 'book1'),
(99, 'Why have you changed jobs so frequently over the past X years?', '你為什麼在過去幾年中頻繁更換工作？', 'career_history', '{job_hopping,stability,explanation}', 3, '{all}', 'book1'),
(100, 'Why haven''t you been promoted?', '你為什麼一直沒有獲得升遷？', 'career_history', '{promotion,career_growth,explanation}', 3, '{mid,senior}', 'book1'),
(101, 'Why should we give you the job over the other candidates?', '我們為什麼要錄用你而不是其他候選人？', 'self_assessment', '{differentiation,value_proposition,persuasion}', 2, '{all}', 'book1'),
(102, 'Why would you accept a lesser salary than what you made before? Won''t you jump ship when a better offer comes along?', '你為什麼願意接受比之前更低的薪資？當有更好的機會出現時，你是否會離職？', 'salary_comp', '{salary,retention,commitment}', 3, '{senior,career_changer}', 'book1'),
(103, 'Are you a leader or a follower?', '你是領導者還是追隨者？', 'management_leadership', '{leadership,self_awareness,role}', 1, '{all}', 'book2'),
(104, 'Are you better at "managing up" or "managing down"?', '你更擅長「向上管理」還是「向下管理」？', 'management_leadership', '{management,leadership,self_awareness}', 2, '{mid,senior}', 'book2'),
(105, 'Are you willing to travel? (How much are you willing to travel?)', '你願意出差嗎？（你願意出差多少？）', 'situational', '{travel,flexibility,logistics}', 1, '{all}', 'book2'),
(106, 'Assume you come to work here. One year from now you go home at the end of the week and think that this is the best job you''ve ever had. What happened to make you feel that way?', '假設你來這裡工作。一年後的某個週末，你回到家覺得這是你做過最好的工作。是什麼讓你有這種感覺？', 'motivation_values', '{ideal_job,values,vision}', 2, '{all}', 'book2'),
(107, 'Describe a time when you were asked to do something you weren''t trained to do. How did you handle it?', '描述一次你被要求做一件你未曾受過訓練的事情的經歷。你是如何處理的？', 'behavioral', '{adaptability,learning,initiative}', 2, '{all}', 'book2'),
(108, 'Describe a time when your team did not agree.', '描述一次你的團隊意見不一致的經歷。', 'behavioral', '{teamwork,conflict,consensus}', 2, '{all}', 'book2'),
(109, 'Describe a time you reduced costs or improved efficiency.', '描述一次你降低成本或提升效率的經歷。', 'behavioral', '{efficiency,cost_reduction,impact}', 2, '{mid,senior}', 'book2'),
(110, 'Describe a work or school instance where you messed up.', '描述一次你在工作或學校中犯錯的經歷。', 'behavioral', '{failure,honesty,learning}', 2, '{all}', 'book2'),
(111, 'Describe how you would complete [a typical task on this job].', '描述你會如何完成這份工作中的一項典型任務。', 'situational', '{task_execution,process,skills}', 2, '{all}', 'book2'),
(112, 'Describe the boss who could get the very best work from you.', '描述什麼樣的主管能讓你發揮出最佳的工作表現。', 'culture_fit', '{management,preferences,work_style}', 2, '{all}', 'book2'),
(113, 'Discuss your educational background.', '談談你的教育背景。', 'career_history', '{education,background,qualifications}', 1, '{entry,all}', 'book2'),
(114, 'Discuss your resume.', '談談你的履歷。', 'career_history', '{resume,experience,career_path}', 1, '{all}', 'book2'),
(115, 'Do you know anyone who works for us?', '你認識在我們公司工作的人嗎？', 'company_knowledge', '{networking,connections,referral}', 1, '{all}', 'book2'),
(116, 'Does a company need B players? Or is it better off only having A players on staff, and why?', '公司是否需要B級人才？還是只有A級人才會更好？為什麼？', 'curveball', '{critical_thinking,team_dynamics,opinion}', 3, '{mid,senior}', 'book2'),
(117, 'Give an example of a political situation you''ve dealt with on the job.', '舉一個你在工作中處理過辦公室政治情況的例子。', 'behavioral', '{politics,interpersonal,navigation}', 3, '{mid,senior}', 'book2'),
(118, 'Give an example of how you set goals and achieve them.', '舉一個你如何設定目標並達成的例子。', 'behavioral', '{goals,achievement,planning}', 1, '{all}', 'book2'),
(119, 'Give an example of how you were able to motivate employees or co-workers.', '舉一個你如何激勵員工或同事的例子。', 'management_leadership', '{motivation,leadership,teamwork}', 2, '{mid,senior}', 'book2'),
(120, 'Give an example of how you worked on a team.', '舉一個你在團隊中工作的例子。', 'behavioral', '{teamwork,collaboration,role}', 1, '{all}', 'book2'),
(121, 'Have you ever fired someone?', '你曾經開除過人嗎？', 'management_leadership', '{firing,management,difficult_decisions}', 3, '{senior}', 'book2'),
(122, 'Have you had to turn an employee with a bad attitude into one with a good attitude?', '你是否曾經將態度不佳的員工轉變為態度良好的員工？', 'management_leadership', '{management,coaching,attitude}', 2, '{mid,senior}', 'book2'),
(123, 'How did you hear about this position?', '你是怎麼知道這個職位的？', 'company_knowledge', '{sourcing,networking,interest}', 1, '{all}', 'book2'),
(124, 'How did you prepare for this interview?', '你為這次面試做了哪些準備？', 'company_knowledge', '{preparation,research,effort}', 1, '{all}', 'book2'),
(125, 'How do I rate as an interviewer?', '你認為我作為面試官的表現如何？', 'curveball', '{awkward,diplomacy,composure}', 3, '{all}', 'book2'),
(126, 'How do you balance life and work?', '你如何平衡生活和工作？', 'culture_fit', '{work_life_balance,priorities,wellness}', 1, '{all}', 'book2'),
(127, 'How do you compensate for your weaknesses?', '你如何彌補自己的弱點？', 'strengths_weaknesses', '{weaknesses,self_improvement,strategy}', 2, '{all}', 'book2'),
(128, 'How do you feel about an income made up totally of commissions?', '你對收入完全由佣金組成的薪酬結構有什麼看法？', 'salary_comp', '{compensation,commissions,risk}', 2, '{all}', 'book2'),
(129, 'How do you feel about working for a younger manager?', '你對為比你年輕的主管工作有什麼看法？', 'culture_fit', '{age,management,adaptability}', 2, '{mid,senior}', 'book2'),
(130, 'How do you make decisions?', '你如何做決定？', 'behavioral', '{decision_making,process,judgment}', 2, '{all}', 'book2'),
(131, 'How do you take advantage of your strengths?', '你如何發揮自己的優勢？', 'strengths_weaknesses', '{strengths,self_awareness,strategy}', 1, '{all}', 'book2'),
(132, 'How does this position compare with others you''re applying for?', '這個職位與你正在申請的其他職位相比如何？', 'situational', '{comparison,job_search,honesty}', 2, '{all}', 'book2'),
(133, 'How does your previous experience relate to this position?', '你之前的經驗與這個職位有什麼關聯？', 'career_history', '{relevance,experience,fit}', 1, '{all}', 'book2'),
(134, 'How have you handled difficult situations with employees?', '你如何處理與員工之間的困難情況？', 'management_leadership', '{management,conflict,leadership}', 2, '{mid,senior}', 'book2'),
(135, 'How many tennis balls can you fit into a limousine?', '一台加長型禮車裡可以裝進多少顆網球？', 'curveball', '{estimation,problem_solving,logic}', 3, '{all}', 'book2');
