
INSERT INTO public.interview_questions (id, question_en, question_zh, category, tags, difficulty, audience, source) VALUES
(1, 'Are you overqualified for this job?', '你是否資歷過高，不適合這份工作？', 'career_history', '{experience,fit,seniority}', 3, '{senior,career_changer}', 'book1'),
(2, 'Are you willing to relocate?', '你願意搬遷嗎？', 'situational', '{relocation,flexibility,logistics}', 1, '{all}', 'book1'),
(3, 'Describe a time when your work was criticized and how you handled it.', '描述一次你的工作被批評的經歷，以及你如何處理。', 'behavioral', '{criticism,feedback,resilience}', 2, '{all}', 'book1'),
(4, 'Describe a time when your workload was heavy and how you handled it.', '描述一次你工作量繁重的經歷，以及你如何處理。', 'behavioral', '{workload,time_management,pressure}', 2, '{all}', 'book1'),
(5, 'Describe how you would handle a situation if you were required to finish multiple tasks by the end of the day, and there was no conceivable way that you could finish them.', '描述如果你被要求在當天下班前完成多項任務，但根本不可能全部完成，你會如何處理這種情況。', 'situational', '{prioritization,time_management,pressure}', 2, '{all}', 'book1'),
(6, 'Describe your work style.', '描述你的工作風格。', 'self_assessment', '{work_style,self_awareness,collaboration}', 1, '{all}', 'book1'),
(7, 'Describe yourself to me in one word.', '用一個詞來形容你自己。', 'self_assessment', '{self_awareness,personal_brand,conciseness}', 2, '{all}', 'book1'),
(8, 'Do you prefer working in a team or alone?', '你喜歡團隊合作還是獨立工作？', 'culture_fit', '{teamwork,work_style,collaboration}', 1, '{all}', 'book1'),
(9, 'Give me a specific example of a time when you had to conform to a policy with which you did not agree.', '舉一個具體的例子，說明你曾經必須遵守一項你不認同的政策。', 'behavioral', '{compliance,disagreement,adaptability}', 2, '{all}', 'book1'),
(10, 'Give me an example of a time that you felt you went above and beyond the call of duty at work.', '舉一個你在工作中超越職責範圍的例子。', 'behavioral', '{initiative,dedication,achievement}', 2, '{all}', 'book1'),
(11, 'Have you ever been on a team where someone was not pulling their own weight? How did you handle it?', '你是否曾經在一個團隊中，有成員沒有盡到自己的責任？你如何處理？', 'behavioral', '{teamwork,conflict,accountability}', 2, '{all}', 'book1'),
(12, 'Have you ever had difficulty working with a supervisor or manager?', '你是否曾經在與主管或經理合作時遇到困難？', 'behavioral', '{conflict,management,relationships}', 2, '{all}', 'book1'),
(13, 'How can you apply your specific skills to help the organization achieve sustainable growth and generate revenue?', '你如何運用你的專業技能，幫助組織實現永續成長並創造營收？', 'self_assessment', '{value_proposition,skills,business_impact}', 3, '{mid,senior}', 'book1'),
(14, 'How did you deal with the situation the last time your boss chastised you or strongly disagreed with a statement, a plan or a decision you made?', '上一次你的主管嚴厲批評你，或強烈反對你的想法、計畫或決定時，你是如何處理的？', 'behavioral', '{conflict,feedback,boss_relationship}', 3, '{all}', 'book1'),
(15, 'How do I know you still have the ''fire in the belly'' to do this job?', '我如何確定你對這份工作仍然保有熱情與動力？', 'motivation_values', '{motivation,passion,drive}', 3, '{senior,career_changer}', 'book1'),
(16, 'How do you deal with difficult customers?', '你如何應對難以處理的客戶？', 'situational', '{customer_service,conflict_resolution,communication}', 2, '{all}', 'book1'),
(17, 'How do you deal with stressful situations?', '你如何應對壓力大的情況？', 'behavioral', '{stress,coping,resilience}', 1, '{all}', 'book1'),
(18, 'How do you evaluate success?', '你如何評估成功？', 'motivation_values', '{success,values,self_awareness}', 2, '{all}', 'book1'),
(19, 'How do you handle stress and pressure on the job?', '你如何處理工作上的壓力？', 'behavioral', '{stress,pressure,coping}', 1, '{all}', 'book1'),
(20, 'How do you rate yourself as a professional?', '你如何評價自己作為一名專業人士的表現？', 'self_assessment', '{self_awareness,professional_development,confidence}', 2, '{all}', 'book1'),
(21, 'How does this position fit in with the career path you envision for yourself?', '這個職位如何符合你為自己規劃的職涯路徑？', 'career_history', '{career_path,goals,fit}', 2, '{all}', 'book1'),
(22, 'How have you responded to a colleague who is putting you down at work?', '你如何回應一位在工作中貶低你的同事？', 'behavioral', '{conflict,workplace_relationships,assertiveness}', 2, '{all}', 'book1'),
(23, 'How long will it take for you to make a significant contribution?', '你預計需要多長時間才能做出重大貢獻？', 'self_assessment', '{onboarding,impact,confidence}', 2, '{mid,senior}', 'book1'),
(24, 'How long would you plan to stay with us?', '你打算在我們公司待多久？', 'career_history', '{retention,commitment,loyalty}', 2, '{all}', 'book1'),
(25, 'How much money did / do you make?', '你過去／目前的薪資是多少？', 'salary_comp', '{salary,compensation,history}', 3, '{all}', 'book1'),
(26, 'How was your working relationship with your previous supervisor?', '你與前任主管的工作關係如何？', 'behavioral', '{boss_relationship,collaboration,communication}', 2, '{all}', 'book1'),
(27, 'How would you feel about working for someone who knows less than you?', '如果要為一位在專業知識上不如你的主管工作，你會如何看待？', 'culture_fit', '{humility,management,adaptability}', 2, '{mid,senior}', 'book1'),
(28, 'How would you go about establishing your credibility quickly with the team?', '你會如何在團隊中快速建立你的信譽？', 'situational', '{onboarding,leadership,credibility}', 2, '{mid,senior}', 'book1'),
(29, 'I noticed that you are applying for a position that is not as senior as your past positions.', '我注意到你正在應徵一個不如你過去職位資深的職位。', 'career_history', '{demotion,career_change,seniority}', 3, '{senior,career_changer}', 'book1'),
(30, 'Why would you consider a job that is, in effect, a demotion for you?', '你為什麼會考慮一份實際上是降職的工作？', 'career_history', '{demotion,motivation,career_change}', 3, '{senior,career_changer}', 'book1'),
(31, 'If we hire you, what will we know about you a year down the road?', '如果我們錄用你，一年後我們會對你有什麼樣的認識？', 'self_assessment', '{future,self_awareness,value_proposition}', 2, '{all}', 'book1'),
(32, 'If you could be any animal, which one would you be and why?', '如果你可以變成任何動物，你會選哪一種？為什麼？', 'curveball', '{creativity,personality,fun}', 2, '{all}', 'book1'),
(33, 'If you could relive the last 10 years of your life, what would you do differently?', '如果你可以重新度過過去十年的人生，你會有什麼不同的做法？', 'self_assessment', '{reflection,self_awareness,growth}', 3, '{mid,senior}', 'book1'),
(34, 'If you had to choose one, would you consider yourself a big-picture person or a detail-oriented person?', '如果你必須二選一，你會認為自己是宏觀思維的人還是注重細節的人？', 'self_assessment', '{work_style,self_awareness,thinking_style}', 1, '{all}', 'book1'),
(35, 'If you were a tree, what kind of a tree would you be?', '如果你是一棵樹，你會是什麼樹？', 'curveball', '{creativity,personality,fun}', 2, '{all}', 'book1'),
(36, 'Is there anything I haven''t told you about the company that you''d like to know?', '有沒有關於公司我還沒告訴你，而你想知道的事情？', 'company_knowledge', '{research,curiosity,engagement}', 1, '{all}', 'book1'),
(37, 'Situational Response Question: An airplane landed in the parking lot. What would you do?', '情境題：一架飛機降落在停車場。你會怎麼做？', 'curveball', '{problem_solving,creativity,composure}', 3, '{all}', 'book1'),
(38, 'Tell me about a time when you disagreed with your boss about a way that something should be done. How did you handle that?', '描述一次你與主管在做事方式上意見不一致的經歷。你是如何處理的？', 'behavioral', '{conflict,boss_relationship,communication}', 2, '{all}', 'book1'),
(39, 'Tell me about a time when you faced a difficult situation with a co-worker.', '描述一次你與同事之間面臨困難情況的經歷。', 'behavioral', '{conflict,teamwork,interpersonal}', 2, '{all}', 'book1'),
(40, 'Tell me about a time when you failed.', '描述一次你失敗的經歷。', 'behavioral', '{failure,resilience,learning}', 2, '{all}', 'book1'),
(41, 'Tell me about a time when you had to give someone difficult feedback. How did you handle it?', '描述一次你必須給予他人負面回饋的經歷。你是如何處理的？', 'behavioral', '{feedback,communication,leadership}', 2, '{mid,senior}', 'book1'),
(42, 'Tell me about yourself.', '請介紹一下你自己。', 'self_assessment', '{introduction,personal_brand,elevator_pitch}', 1, '{all}', 'book1'),
(43, 'Tell me your life story (more of your personal history).', '請分享你的人生故事（更多關於你的個人背景）。', 'self_assessment', '{personal_history,storytelling,background}', 2, '{all}', 'book1'),
(44, 'Tell us about a failed project.', '請描述一個失敗的專案。', 'behavioral', '{failure,project_management,learning}', 2, '{mid,senior}', 'book1'),
(45, 'Tell us about a time that you went against corporate directives. Why? How did it turn out?', '請描述一次你違反公司指令的經歷。原因是什麼？結果如何？', 'behavioral', '{risk_taking,integrity,judgment}', 3, '{mid,senior}', 'book1'),
(46, 'There''s no right or wrong answer, but if you could be anywhere in the world right now, where would you be?', '這題沒有標準答案，但如果你現在可以在世界上任何地方，你會選擇哪裡？', 'curveball', '{personality,creativity,values}', 1, '{all}', 'book1'),
(47, 'We are looking for someone with experience…or, you don''t have enough experience—why should we hire you?', '我們在尋找有經驗的人……或者說，你的經驗不夠，我們為什麼應該錄用你？', 'career_history', '{experience,value_proposition,persuasion}', 3, '{entry,career_changer}', 'book1'),
(48, 'What are some of your greatest and/or proudest accomplishments?', '你最大的成就，或你最引以為傲的成就是什麼？', 'strengths_weaknesses', '{achievements,pride,impact}', 1, '{all}', 'book1'),
(49, 'What are your advantages and disadvantages?', '你的優點和缺點是什麼？', 'strengths_weaknesses', '{strengths,weaknesses,self_awareness}', 2, '{all}', 'book1'),
(50, 'What are your hobbies?', '你的興趣愛好是什麼？', 'culture_fit', '{hobbies,personality,culture}', 1, '{all}', 'book1'),
(51, 'What are your least favorite things to do in your role as X?', '在你擔任X的角色中，你最不喜歡做的事情是什麼？', 'self_assessment', '{preferences,honesty,self_awareness}', 2, '{all}', 'book1'),
(52, 'What are your pet peeves?', '你最無法忍受的事情是什麼？', 'culture_fit', '{personality,workplace,honesty}', 2, '{all}', 'book1'),
(53, 'What are your salary expectations?', '你的期望薪資是多少？', 'salary_comp', '{salary,negotiation,expectations}', 3, '{all}', 'book1'),
(54, 'What are your workplace values?', '你的職場價值觀是什麼？', 'motivation_values', '{values,culture,principles}', 1, '{all}', 'book1'),
(55, 'What did you earn at your last job?', '你上一份工作的薪資是多少？', 'salary_comp', '{salary,history,compensation}', 3, '{all}', 'book1'),
(56, 'What did you like or dislike about your previous jobs?', '你喜歡或不喜歡上一份工作的哪些方面？', 'career_history', '{past_jobs,preferences,honesty}', 1, '{all}', 'book1'),
(57, 'What do people most often criticize about you?', '別人最常批評你的是什麼？', 'strengths_weaknesses', '{criticism,self_awareness,weaknesses}', 3, '{all}', 'book1'),
(58, 'What do you consider to be your most significant accomplishment?', '你認為你最重要的成就是什麼？', 'strengths_weaknesses', '{achievements,impact,pride}', 2, '{all}', 'book1'),
(59, 'What do you expect from a supervisor?', '你對主管有什麼期待？', 'culture_fit', '{management,expectations,work_style}', 1, '{all}', 'book1'),
(60, 'What do you know about this company?', '你對這家公司了解多少？', 'company_knowledge', '{research,preparation,interest}', 1, '{all}', 'book1'),
(61, 'What do you wish you''d done better?', '你希望自己哪些方面能做得更好？', 'self_assessment', '{reflection,growth,self_awareness}', 2, '{all}', 'book1'),
(62, 'What excites you and scares you about this position?', '這個職位讓你感到興奮與擔憂的分別是什麼？', 'motivation_values', '{honesty,motivation,self_awareness}', 2, '{all}', 'book1'),
(63, 'What have you been doing since you got laid off?', '被裁員之後你都在做什麼？', 'career_history', '{unemployment,gap,resilience}', 3, '{career_changer}', 'book1'),
(64, 'What have you learned from your mistakes?', '你從錯誤中學到了什麼？', 'behavioral', '{failure,learning,growth}', 1, '{all}', 'book1'),
(65, 'What is good customer service?', '什麼是好的客戶服務？', 'situational', '{customer_service,values,definition}', 1, '{all}', 'book1'),
(66, 'What''s Your Greatest Weakness?', '你最大的弱點是什麼？', 'strengths_weaknesses', '{weaknesses,self_awareness,honesty}', 2, '{all}', 'book1'),
(67, 'What is your ideal job?', '你理想的工作是什麼？', 'motivation_values', '{ideal_job,values,career_goals}', 2, '{all}', 'book1'),
(68, 'What is your least favorite managerial task?', '你最不喜歡的管理任務是什麼？', 'management_leadership', '{management,preferences,honesty}', 2, '{mid,senior}', 'book1');
