
-- Enable pg_trgm extension for fuzzy search
CREATE EXTENSION IF NOT EXISTS pg_trgm;

-- Create interview_questions table
CREATE TABLE public.interview_questions (
  id int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  question_en text NOT NULL,
  question_zh text NOT NULL,
  category text NOT NULL,
  tags text[] NOT NULL,
  difficulty int2 NOT NULL,
  audience text[] NOT NULL,
  source text
);

-- Enable RLS
ALTER TABLE public.interview_questions ENABLE ROW LEVEL SECURITY;

-- Public read-only access
CREATE POLICY "Public read access" ON public.interview_questions
  FOR SELECT TO anon, authenticated
  USING (true);

-- Indexes
CREATE INDEX idx_questions_tags ON public.interview_questions USING GIN (tags);
CREATE INDEX idx_questions_audience ON public.interview_questions USING GIN (audience);
CREATE INDEX idx_questions_category ON public.interview_questions (category);
CREATE INDEX idx_questions_difficulty ON public.interview_questions (difficulty);
CREATE INDEX idx_questions_fts ON public.interview_questions USING GIN (to_tsvector('english', question_en));
CREATE INDEX idx_questions_trgm_en ON public.interview_questions USING GIN (question_en gin_trgm_ops);
CREATE INDEX idx_questions_trgm_zh ON public.interview_questions USING GIN (question_zh gin_trgm_ops);
