
INSERT INTO public.interview_questions (id, question_en, question_zh, category, tags, difficulty, audience, source) VALUES
(136, 'How will you identify problems and opportunities on the job?', '你會如何在工作中發現問題與機會？', 'situational', '{problem_solving,initiative,analytical}', 2, '{mid,senior}', 'book2'),
(137, 'How would people you have worked with describe you?', '與你共事過的人會如何形容你？', 'self_assessment', '{reputation,personality,references}', 1, '{all}', 'book2'),
(138, 'How would you guide an alien through making a peanut butter sandwich?', '你會如何引導一個外星人製作花生醬三明治？', 'curveball', '{communication,creativity,instructions}', 2, '{all}', 'book2'),
(139, 'I see you had an internship. Did you pursue a full-time job with them? What happened?', '我注意到你曾經實習過。你有爭取該公司的正職工作嗎？後來如何？', 'career_history', '{internship,early_career,explanation}', 1, '{entry}', 'book2'),
(140, 'If I were to ask your current boss to tell me one thing you do that drives them crazy, what would they say?', '如果我問你現任主管，你做的哪一件事最讓他們困擾，他們會怎麼說？', 'strengths_weaknesses', '{weaknesses,boss_relationship,honesty}', 3, '{all}', 'book2'),
(141, 'If I were to ask your current boss what your greatest strength is, what would they say?', '如果我問你現任主管你最大的優點是什麼，他們會怎麼說？', 'strengths_weaknesses', '{strengths,boss_relationship,reputation}', 1, '{all}', 'book2'),
(142, 'If you are employed, how are you managing time to interview?', '如果你目前在職，你是如何安排時間來面試的？', 'situational', '{time_management,job_search,logistics}', 1, '{all}', 'book2'),
(143, 'If you could choose any company to work for, which one would it be?', '如果你可以選擇任何一家公司工作，你會選哪一家？', 'motivation_values', '{ideal_company,values,aspiration}', 2, '{all}', 'book2'),
(144, 'If you get the job, how could you lose or make money for me?', '如果你獲得這份工作，你會如何為我賺錢或造成虧損？', 'self_assessment', '{business_impact,value_proposition,risk}', 3, '{mid,senior}', 'book2'),
(145, 'If you knew things at your company were rocky, why didn''t you get out sooner?', '如果你知道公司的狀況不穩定，你為什麼沒有早點離開？', 'career_history', '{judgment,loyalty,explanation}', 3, '{all}', 'book2'),
(146, 'If you were at a business lunch and you ordered a rare steak and they brought it to you well-done, what would you do?', '如果你在商務午餐中點了三分熟的牛排，但送來的是全熟的，你會怎麼做？', 'curveball', '{personality,conflict_resolution,composure}', 2, '{all}', 'book2'),
(147, 'If you were running a company that produces X and the market was tanking for that product, what would you do?', '如果你經營一家生產X的公司，而該產品的市場正在萎縮，你會怎麼做？', 'situational', '{strategy,problem_solving,business_acumen}', 3, '{mid,senior}', 'book2'),
(148, 'If you were the CEO of this company, what are the top 2 things you would do?', '如果你是這家公司的執行長，你會優先做的兩件事是什麼？', 'company_knowledge', '{strategy,vision,business_acumen}', 3, '{mid,senior}', 'book2'),
(149, 'If you won the lottery, would you still work?', '如果你中了樂透，你還會繼續工作嗎？', 'motivation_values', '{motivation,passion,work_ethic}', 1, '{all}', 'book2'),
(150, 'Is it more important to be lucky or skillful?', '幸運和技能哪個更重要？', 'curveball', '{philosophy,opinion,critical_thinking}', 2, '{all}', 'book2'),
(151, 'Is there any question I haven''t asked you that I should?', '有沒有我應該問你但尚未問到的問題？', 'self_assessment', '{initiative,preparation,value_proposition}', 2, '{all}', 'book2'),
(152, 'It''s your dime. (Interviewer doesn''t ask questions)', '由你來主導。（面試官不提問）', 'curveball', '{initiative,communication,composure}', 3, '{all}', 'book2'),
(153, 'Tell me a suggestion you have made that was implemented.', '請分享一個你提出並被採納實施的建議。', 'behavioral', '{initiative,impact,influence}', 2, '{all}', 'book2'),
(154, 'Tell me about a time when you helped someone.', '描述一次你幫助他人的經歷。', 'behavioral', '{helpfulness,teamwork,empathy}', 1, '{all}', 'book2'),
(155, 'Tell me about a time when you misjudged a person.', '描述一次你看錯一個人的經歷。', 'behavioral', '{judgment,self_awareness,learning}', 2, '{all}', 'book2'),
(156, 'Tell me about a time you conveyed technical information to a non-technical audience.', '描述一次你向非技術背景的人傳達技術資訊的經歷。', 'behavioral', '{communication,technical,simplification}', 2, '{mid,senior}', 'book2'),
(157, 'Tell me about a time you had to take initiative.', '描述一次你必須主動採取行動的經歷。', 'behavioral', '{initiative,proactivity,leadership}', 1, '{all}', 'book2'),
(158, 'Tell me about a time you planned and coordinated a project from start to finish.', '描述一次你從頭到尾規劃並執行一個專案的經歷。', 'behavioral', '{project_management,planning,execution}', 2, '{mid,senior}', 'book2'),
(159, 'Tell me about a work incident in which you were totally honest, despite a potential risk or downside.', '描述一次你在工作中完全誠實的經歷，即使可能帶有風險或負面後果。', 'behavioral', '{integrity,honesty,risk}', 2, '{all}', 'book2'),
(160, 'Tell me about the last time you were angry or upset at work. What happened?', '描述你上一次在工作中感到憤怒或沮喪的經歷。發生了什麼事？', 'behavioral', '{emotions,composure,conflict}', 2, '{all}', 'book2'),
(161, 'Tell me about the toughest negotiation you''ve ever been in.', '描述你經歷過最艱難的一次談判。', 'behavioral', '{negotiation,persuasion,conflict}', 3, '{mid,senior}', 'book2'),
(162, 'Tell me about the worst boss you''ve ever had.', '描述你遇過最差的主管。', 'behavioral', '{boss_relationship,honesty,diplomacy}', 2, '{all}', 'book2'),
(163, 'Tell me about your current (most recent) employer (i.e. what do they do, how long they''ve been in business, etc.).', '請介紹你目前（最近）的雇主（例如公司業務內容、營運時間等）。', 'career_history', '{current_employer,context,knowledge}', 1, '{all}', 'book2'),
(164, 'Under what circumstances have you found it acceptable to break confidence?', '在什麼情況下你認為打破保密承諾是可以接受的？', 'situational', '{ethics,judgment,integrity}', 3, '{all}', 'book2'),
(165, 'Walk me through your career from the start to where it is now.', '請從頭開始，帶我了解你的職涯發展至今。', 'career_history', '{career_path,storytelling,background}', 1, '{all}', 'book2'),
(166, 'What are some of your leadership experiences?', '你有哪些領導經驗？', 'management_leadership', '{leadership,experience,examples}', 1, '{mid,senior}', 'book2'),
(167, 'What are the most important qualities of successful people? How do you rate yourself in those areas?', '你認為成功人士最重要的特質是什麼？你在這些方面如何評價自己？', 'self_assessment', '{success,self_awareness,qualities}', 2, '{all}', 'book2'),
(168, 'What are your long-term career goals?', '你的長期職涯目標是什麼？', 'career_history', '{career_goals,ambition,planning}', 1, '{all}', 'book2'),
(169, 'What changes have you made in working with others to be more effective at work?', '你在與他人合作方面做了哪些改變，以提高工作效率？', 'behavioral', '{collaboration,self_improvement,adaptability}', 2, '{all}', 'book2'),
(170, 'What circumstances bring you here today?', '是什麼原因促使你今天前來面試？', 'career_history', '{motivation,job_search,context}', 1, '{all}', 'book2'),
(171, 'What do you do to grow your skills and knowledge of the job/industry?', '你做了什麼來提升自己的專業技能與產業知識？', 'motivation_values', '{professional_development,learning,growth}', 1, '{all}', 'book2'),
(172, 'What do you expect from this job?', '你對這份工作有什麼期望？', 'motivation_values', '{expectations,fit,values}', 1, '{all}', 'book2'),
(173, 'What gets you up in the morning?', '每天早上是什麼驅使你起床？', 'motivation_values', '{motivation,passion,drive}', 1, '{all}', 'book2'),
(174, 'What have you learned from all the different roles you''ve had?', '你從過去不同的工作經歷中學到了什麼？', 'career_history', '{learning,career_path,growth}', 2, '{all}', 'book2'),
(175, 'What historical figure do you admire and why?', '你欣賞哪位歷史人物？為什麼？', 'curveball', '{personality,values,knowledge}', 2, '{all}', 'book2'),
(176, 'What if you worked for someone who managed to take credit for all your great ideas? How would you handle it?', '如果你的主管將你所有的好點子據為己有，你會如何處理？', 'situational', '{conflict,boss_relationship,assertiveness}', 2, '{all}', 'book2'),
(177, 'What is one thing you''d like to do better? What is your plan for accomplishing that?', '你最想改善的一件事是什麼？你打算如何做到？', 'strengths_weaknesses', '{self_improvement,planning,self_awareness}', 2, '{all}', 'book2'),
(178, 'What is the last book you read for fun? (Or, what is your favorite book?)', '你最近閱讀的一本休閒書籍是什麼？（或者，你最喜歡的書是什麼？）', 'culture_fit', '{reading,personality,interests}', 1, '{all}', 'book2'),
(179, 'What is the most courageous action or unpopular stand that you have ever taken?', '你曾經做過最有勇氣的行動，或採取過最不受歡迎的立場是什麼？', 'behavioral', '{courage,integrity,risk}', 3, '{all}', 'book2'),
(180, 'What is the most important thing you''re looking for in a company/job besides salary?', '除了薪資之外，你在公司／工作中最看重的是什麼？', 'motivation_values', '{values,priorities,culture}', 1, '{all}', 'book2'),
(181, 'What is your biggest weakness that''s really a weakness and not a secret strength?', '你最大的弱點是什麼？請說出真正的弱點，而非包裝成優點的缺點。', 'strengths_weaknesses', '{weaknesses,honesty,self_awareness}', 3, '{all}', 'book2'),
(182, 'What is your favorite website?', '你最喜歡的網站是什麼？', 'culture_fit', '{interests,personality,digital}', 1, '{all}', 'book2'),
(183, 'What qualities in your co-workers bother you most? What do you appreciate most?', '你的同事有哪些特質最讓你困擾？哪些最讓你欣賞？', 'culture_fit', '{teamwork,preferences,workplace}', 2, '{all}', 'book2'),
(184, 'What tools or techniques do you use to stay organized and increase your productivity?', '你使用哪些工具或方法來保持條理並提高工作效率？', 'self_assessment', '{organization,productivity,tools}', 1, '{all}', 'book2'),
(185, 'What will your job references say about you?', '你的工作推薦人會如何評價你？', 'self_assessment', '{references,reputation,confidence}', 2, '{all}', 'book2'),
(186, 'What would the person who likes you least in the world say about you?', '全世界最不喜歡你的人會如何評價你？', 'strengths_weaknesses', '{weaknesses,honesty,self_awareness}', 3, '{all}', 'book2'),
(187, 'What would you do if management made a decision you didn''t agree with?', '如果管理階層做了一個你不認同的決定，你會怎麼做？', 'situational', '{disagreement,compliance,judgment}', 2, '{all}', 'book2'),
(188, 'What would you do if you found out the company you worked for was doing something illegal?', '如果你發現你任職的公司正在從事違法行為，你會怎麼做？', 'situational', '{ethics,integrity,judgment}', 3, '{all}', 'book2'),
(189, 'What would you do if you got behind schedule with your part of a project?', '如果你負責的專案部分進度落後，你會怎麼做？', 'situational', '{time_management,accountability,problem_solving}', 1, '{all}', 'book2'),
(190, 'What would you do if you made an important business decision and a co-worker challenged it?', '如果你做了一個重要的商業決定，而一位同事提出質疑，你會怎麼做？', 'situational', '{conflict,decision_making,composure}', 2, '{mid,senior}', 'book2'),
(191, 'What would you look to accomplish in the first 30 days/60 days/90 days on the job?', '你在到職的前30天、60天、90天，預計達成什麼目標？', 'situational', '{onboarding,planning,initiative}', 2, '{mid,senior}', 'book2'),
(192, 'What would your direct reports say about you?', '你的直屬部屬會如何評價你？', 'management_leadership', '{management,reputation,leadership}', 2, '{mid,senior}', 'book2'),
(193, 'What, as an organization, can we offer that is better than your current employer?', '作為一個組織，我們能提供什麼是你目前雇主無法提供的？', 'motivation_values', '{motivation,comparison,expectations}', 2, '{all}', 'book2'),
(194, 'What''s your favorite dish, and how would you convince someone who hated an ingredient in it to try it?', '你最喜歡的菜餚是什麼？你會如何說服一個討厭其中某種食材的人嘗試？', 'curveball', '{persuasion,creativity,personality}', 2, '{all}', 'book2'),
(195, 'When would you be available to start?', '你什麼時候可以開始上班？', 'situational', '{availability,logistics,transition}', 1, '{all}', 'book2'),
(196, 'Who are our competitors?', '我們的競爭對手有哪些？', 'company_knowledge', '{research,industry_knowledge,preparation}', 2, '{all}', 'book2'),
(197, 'Who are the influencers in your life?', '你人生中對你影響最大的人是誰？', 'motivation_values', '{values,mentors,personality}', 1, '{all}', 'book2'),
(198, 'Who do you follow on Twitter and why?', '你在Twitter上追蹤誰？為什麼？', 'culture_fit', '{interests,digital,personality}', 1, '{all}', 'book2'),
(199, 'Why did you get into this line of work? (choose this as a career)', '你當初為什麼選擇這個行業？', 'career_history', '{career_choice,motivation,passion}', 1, '{all}', 'book2'),
(200, 'Why don''t you want to give me your salary requirements?', '你為什麼不願意告訴我你的期望薪資？', 'salary_comp', '{salary,negotiation,pushback}', 3, '{all}', 'book2'),
(201, 'Will you be out to take my job?', '你是否會試圖取代我的職位？', 'curveball', '{ambition,diplomacy,composure}', 2, '{all}', 'book2'),
(202, 'Would you rather be liked or feared?', '你寧願被喜歡還是被敬畏？', 'management_leadership', '{leadership,philosophy,style}', 2, '{mid,senior}', 'book2'),
(203, 'You are changing careers. Why should I let you ''experiment'' with me and basically pay you to learn on the job?', '你正在轉換跑道。為什麼我應該讓你在這裡「實驗」，等於是付薪資讓你邊做邊學？', 'career_history', '{career_change,value_proposition,persuasion}', 3, '{career_changer}', 'book2');

-- Reset the identity sequence
SELECT setval('interview_questions_id_seq', 203);
